name: Publish to NPMJS
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "21.x"
          registry-url: "https://registry.npmjs.org"

      - name: Run install
        run: npm i

      - name: Run build
        run: npm run build

      - name: Publish package on NPM 📦
        run: npm publish --verbose --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET_KEY }}
