name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "21.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies and build 🔧
        run: yarn install --frozen-lockfile && yarn run build
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET_KEY }}
